
⚠ Job (task=0) failed during processing with trace:
----------------------
Traceback (most recent call last):
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/submission.py", line 55, in process_job
    result = delayed.result()
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/utils.py", line 137, in result
    self._result = self.function(*self.args, **self.kwargs)
                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(__main__.evaluate) at 0x7fc564307ec0>", line 31, in evaluate
  File "/home/s3811141/repos/OmniOpt/ax/.omniopt.py", line 2378, in evaluate
    write_job_infos_csv(parameters, stdout, program_string_with_params, exit_code, _signal, result, start_time, end_time, run_time)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(__main__.write_job_infos_csv) at 0x7fc564307e20>", line 176, in write_job_infos_csv
beartype.roar.BeartypeCallHintParamViolation: Function __main__.write_job_infos_csv() parameter start_time=1738566853 violates type hint <class 'float'>, as int 1738566853 not instance of float.

----------------------
You can check full logs with 'job.stderr(0)' and 'job.stdout(0)'or at paths:
  - /home/s3811141/repos/OmniOpt/ax/runs/__main__tests__BOTORCH_MODULAR___nogridsearch/0/single_runs/652293/652293_0_log.err
  - /home/s3811141/repos/OmniOpt/ax/runs/__main__tests__BOTORCH_MODULAR___nogridsearch/0/single_runs/652293/652293_0_log.out


⚠ Job (task=0) failed during processing with trace:
----------------------
Traceback (most recent call last):
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/submission.py", line 55, in process_job
    result = delayed.result()
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/utils.py", line 137, in result
    self._result = self.function(*self.args, **self.kwargs)
                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(__main__.evaluate) at 0x7fc564307ec0>", line 31, in evaluate
  File "/home/s3811141/repos/OmniOpt/ax/.omniopt.py", line 2378, in evaluate
    write_job_infos_csv(parameters, stdout, program_string_with_params, exit_code, _signal, result, start_time, end_time, run_time)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(__main__.write_job_infos_csv) at 0x7fc564307e20>", line 176, in write_job_infos_csv
beartype.roar.BeartypeCallHintParamViolation: Function __main__.write_job_infos_csv() parameter start_time=1738566858 violates type hint <class 'float'>, as int 1738566858 not instance of float.

----------------------
You can check full logs with 'job.stderr(0)' and 'job.stdout(0)'or at paths:
  - /home/s3811141/repos/OmniOpt/ax/runs/__main__tests__BOTORCH_MODULAR___nogridsearch/0/single_runs/652771/652771_0_log.err
  - /home/s3811141/repos/OmniOpt/ax/runs/__main__tests__BOTORCH_MODULAR___nogridsearch/0/single_runs/652771/652771_0_log.out

Best result could not be determined

