
⚠ Job (task=0) failed during processing with trace:
----------------------
Traceback (most recent call last):
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/submission.py", line 55, in process_job
    result = delayed.result()
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/utils.py", line 137, in result
    self._result = self.function(*self.args, **self.kwargs)
                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(__main__.evaluate) at 0x7f9c6c9fbec0>", line 31, in evaluate
  File "/home/s3811141/repos/OmniOpt/ax/.omniopt.py", line 2378, in evaluate
    write_job_infos_csv(parameters, stdout, program_string_with_params, exit_code, _signal)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(__main__.write_job_infos_csv) at 0x7f9c6c9fbe20>", line 111, in write_job_infos_csv
  File "/home/s3811141/repos/OmniOpt/ax/.omniopt.py", line 2293, in write_job_infos_csv
    if isinstance(result, dict): # pragma: no cover
                  ^^^^^^
NameError: name 'result' is not defined

----------------------
You can check full logs with 'job.stderr(0)' and 'job.stdout(0)'or at paths:
  - /home/s3811141/repos/OmniOpt/ax/runs/__main__tests__BOTORCH_MODULAR___nogridsearch/0/single_runs/640963/640963_0_log.err
  - /home/s3811141/repos/OmniOpt/ax/runs/__main__tests__BOTORCH_MODULAR___nogridsearch/0/single_runs/640963/640963_0_log.out


⚠ Job (task=0) failed during processing with trace:
----------------------
Traceback (most recent call last):
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/submission.py", line 55, in process_job
    result = delayed.result()
  File "/home/s3811141/.omniax_x86_64_Python_3.13.1/lib/python3.13/site-packages/submitit/core/utils.py", line 137, in result
    self._result = self.function(*self.args, **self.kwargs)
                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(__main__.evaluate) at 0x7f9c6c9fbec0>", line 31, in evaluate
  File "/home/s3811141/repos/OmniOpt/ax/.omniopt.py", line 2378, in evaluate
    write_job_infos_csv(parameters, stdout, program_string_with_params, exit_code, _signal)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(__main__.write_job_infos_csv) at 0x7f9c6c9fbe20>", line 111, in write_job_infos_csv
  File "/home/s3811141/repos/OmniOpt/ax/.omniopt.py", line 2293, in write_job_infos_csv
    if isinstance(result, dict): # pragma: no cover
                  ^^^^^^
NameError: name 'result' is not defined

----------------------
You can check full logs with 'job.stderr(0)' and 'job.stdout(0)'or at paths:
  - /home/s3811141/repos/OmniOpt/ax/runs/__main__tests__BOTORCH_MODULAR___nogridsearch/0/single_runs/641371/641371_0_log.err
  - /home/s3811141/repos/OmniOpt/ax/runs/__main__tests__BOTORCH_MODULAR___nogridsearch/0/single_runs/641371/641371_0_log.out

Best result could not be determined

